# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Daleko jeszcze?"
description: > # this means to ignore newlines until "email:"
   Osobisty blog do dzielenia się treściami użytecznymi

email: dalekojeszcze.eu@outlook.com
#blog logo
logo: "/assets/images/simple_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/IMG_1153.JPG"

name: 'Tomasz Skierkowski'
author: 'Tomasz Skierkowski'
author_image: "/assets/images/TS_c.JPG"

paginate:	5

url: "https://dalekojeszcze.eu" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dalekojeszcze'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dalekojeszcze
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="
 
  - icon:	instagram
    url:	https://www.instagram.com/dalekojeszcze.eu/
    desc:	Follow me on Instagram
    share_url:
    share_title:
    share_link:
    
#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
