# Site settings
title: Daleko jeszcze?
email: dalekojeszcze@outlook.com
address: 
phone_eeuu: 
phone_uruguay: 
description: > # this means to ignore newlines until "baseurl:"
  Articles by Xmartlabs, sharing the knowledge about full-stack mobile design and development in iOS, Android and Ruby.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dalekojeszcze.eu" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: kramdown
future: false
timezone: America/Montevideo
permalink: /:year/:month/:day/:title/

# sass:
#   style: :compressed

defaults:
  # Default layout and language to everything
  -
    values:
      layout: "default"
  # Specify default pages’ layout
  -
    scope:
      path: "_posts/martin"
      type: "posts"
    values:
      author: "Tomasz"

exclude:
  - README.md
