title: Daleko jeszcze?
description: Garsc tresci uzytecznych
url: "https://dalekojeszcze.eu" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

paginate: 5

gems: [jekyll-paginate]
permalink: /:title.html
